### ISSUE TITLE
Task: implement the Dot Class

### ISSUE THREAD

**Issue by DamirBayazitov** [DamirBayazitov/geometry-objects#6]
# Epic Title

Feature: Dot Class

## Epic Description

This Feature will create a Dot Class.

## List of Tasks (Complete in order)

1. [ ] [Task 1: Implement the function: enter_coordinates](https://github.com/DamirBayazitov/geometry-objects/issues/2)
2. [ ] [Task 2: Implement the function: get_dot_definition](https://github.com/DamirBayazitov/geometry-objects/issues/3)
3. [ ] [Task 3: Implement the function: get_distance](https://github.com/DamirBayazitov/geometry-objects/issues/4)
